### ISSUE TITLE
[bug] Repeater - elements jumps, while typing

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#332] opened 2017-10-16 19:07 UTC
![2017-10-17_02-06-00](https://user-images.githubusercontent.com/2145313/31630117-d8f4b678-b2df-11e7-9cc7-a5c33f39115e.gif)

**Comment by defr0zen** [comment] 2017-11-06 22:13
@Boorj This one is kind-of by design. The problem is that when one of the texts moves to x,y, all others are also moving to x,y. And x,y changes when text-align is center and you start typing.
Maybe text elements should be handled in a special way in the repeater, but that adds too much complication for now.

The best way out of this is to have text mode = block and have all texts of the same size. Maybe when a text

**Closed** 2017-11-06 22:14 UTC
Labels: bug, by-design

**Comment by Boorj** [comment] 2017-11-10 07:42
Let me disagree. You could just link  not X coordinate, but center X when aligned to center, and right X corner, when aligned right. I mean, logic is next: if it's text label, keep `(X + width)` if aligned right, and so on.

**Comment by defr0zen** [comment] 2017-11-10 11:12
Yes, something like this, but it will be more complex since texts can be rotated, flipped, etc... 
The current workaround is just to have all texts have the same width? Is it that inconvenient?

**Comment by Boorj** [comment] 2017-11-12 16:45
I will try next time and report.
