### ISSUE TITLE
[bug] shift click in zoom out

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#187] opened 2017-09-02 05:09 UTC
### repro 
- draw horizontal line
- zoom out
- press shift and start moving the right point of line horizontally 

expected: point is moved straight left / right.
got : point is shifted 1 pixel below.

Problem is that you even can't recognize that on big zoom out. And that could possibly ruin your design a little bit.

![2017-09-02_12-05-47](https://user-images.githubusercontent.com/2145313/29993101-7455d1a0-8fd7-11e7-8bed-8c0dcf038430.gif)
Maybe this `gif` is not the best repesentation, but try your self

**Comment by alex-carbonium** [comment] 2017-09-18 18:19
duplicate of line snapping bug

**Closed by alex-carbonium** 2017-09-18 18:19 UTC
